apiVersion: v1
kind: "Service"
metadata:
    name: "db-clusterip"
    labels:
      app: mysql-pod 
spec:
    type: ClusterIP
    ports:
    - targetPort: 3306
      port: 3306
      name: "db-port"
      protocol: TCP
    selector:
      app: mysql-pod