apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-pod
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-user
                  key: password
          ports:
            - containerPort: 3306
              name: "db-port"
          volumeMounts:
            - name: db-initialdata
              mountPath: /docker-entrypoint-initdb.d
            - name: db-volume
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-persistentvolume-claim
        - name: db-initialdata
          configMap:
            name: mysql-data
