apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-persistentvolume-claim
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests: 
            storage: 10Gi
    volumeName: db-persistent-volume