apiVersion: v1
kind: Service
metadata:
  name: webapi-lb
  labels:
    app: webapi-pod
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9000
      port: 3000
      name: "api-port"
      protocol: TCP
  selector:
    app: webapi-pod

